import { NextResponse } from "next/server";
import { generateIdeaSuggestionsWithClaude } from "@/lib/ai/claude";

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const {
      category = "FUNNY",
      language = "Urdu",
      visualStyle = "3D Cartoon Style",
      videoDuration = 8,
      customDialogue,
      customDialogueSeq1,
      customDialogueSeq2,
      customDialogueSeq3,
      kids20sStep,
      scene1Text,
      scene2Text,
      scene1Clothing,
      seed,
      kidsAge,
      kidsAudioStyle,
      kidsLocation,
      kidsHealth,
      kidsClothing,
      fatherClothing,
      motherClothing,
      kidsExpression,
      kidsFood,
      kidsProp,
      timeOfDay,
      storyBeat,
      cameraShot,
      charPerformance,
      kidsVibe,
      characterSetup,
      charactersPerScene,
      kidsNationality,
      carboxBrand,
      carboxColor,
      carboxPackaging,
      carboxBackground,
      aiModel,
      musicType,
      seriousDialogueStyle,
      customSceneDescription,
      outroEffects,
      includeMic,
      audiencePerspective,
      stageEnvironment,
      initialPerformer,
      triggerAction,
      targetEntity,
      lightingFx,
      performerAge,
      stageLocation,
      songCrowdFx,
      characterFaceType,
      isShortIdea = false,
      withoutDialogue = false,
      withoutMusic = false,
      includeCharacterBible = false,
      compactMode = true,
      referenceCharacterInfo,
    } = body;

    const ideas = await generateIdeaSuggestionsWithClaude({
      category,
      language,
      visualStyle,
      videoDuration: Number(videoDuration),
      customDialogue,
      customDialogueSeq1,
      customDialogueSeq2,
      customDialogueSeq3,
      kids20sStep,
      scene1Text,
      scene2Text,
      scene1Clothing,
      includeCharacterBible: Boolean(includeCharacterBible),
      compactMode: Boolean(compactMode),
      isShortIdea: Boolean(isShortIdea),
      withoutDialogue: Boolean(withoutDialogue),
      withoutMusic: Boolean(withoutMusic),
      kidsAge,
      kidsAudioStyle,
      kidsLocation,
      kidsHealth,
      kidsClothing,
      fatherClothing,
      motherClothing,
      kidsExpression,
      kidsFood,
      kidsProp,
      timeOfDay,
      storyBeat,
      cameraShot,
      charPerformance,
      kidsVibe,
      characterSetup,
      charactersPerScene,
      kidsNationality,
      carboxBrand,
      carboxColor,
      carboxPackaging,
      carboxBackground,
      seed: seed || Date.now(),
      aiModel,
      musicType,
      seriousDialogueStyle,
      customSceneDescription,
      outroEffects,
      includeMic: Boolean(includeMic),
      audiencePerspective,
      stageEnvironment,
      initialPerformer,
      triggerAction,
      targetEntity,
      lightingFx,
      performerAge,
      stageLocation,
      songCrowdFx,
      characterFaceType,
      referenceCharacterInfo,
    });

    return NextResponse.json({ success: true, ideas });
  } catch (error: any) {
    console.error("POST /api/suggest-ideas error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to suggest ideas" },
      { status: 200 }
    );
  }
}
